/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed13;
  GtkWidget *id_entry;
  GtkWidget *password_entry;
  GtkWidget *accederlogin;
  GtkWidget *label115;
  GtkWidget *label116;
  GtkWidget *label114;
  GtkWidget *label113;
  GtkWidget *fixed1;
  GtkWidget *treeviewparking;
  GtkWidget *label6;
  GtkWidget *actualiseraff;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *affecteraff;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *chercherchertrv;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image32;
  GtkWidget *label97;
  GtkWidget *suppaff;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *modifaff;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *ajotaff;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *retauloginbutton1;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image35;
  GtkWidget *label117;
  GtkWidget *label1;
  GtkWidget *fixed2;
  GtkWidget *nompentry2;
  GtkWidget *adrpentry3;
  GtkWidget *entry4;
  GtkWidget *capacitepaentry5;
  GtkWidget *tarifpaentry6;
  GtkObject *spin1_adj;
  GtkWidget *spin1;
  GtkObject *spin2_adj;
  GtkWidget *spin2;
  GtkObject *spin3_adj;
  GtkWidget *spin3;
  GtkObject *spin4_adj;
  GtkWidget *spin4;
  GtkObject *spin5_adj;
  GtkWidget *spin5;
  GtkObject *spin6_adj;
  GtkWidget *spin6;
  GtkWidget *etatpcomboboxentry1;
  GtkWidget *eventbox2;
  GtkWidget *blocpacomboboxentry2;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *abonpacomboboxentry3;
  GtkWidget *radiobutton1;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label104;
  GtkWidget *label103;
  GtkWidget *label99;
  GtkWidget *checkbutton1;
  GtkWidget *menuajout;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label85;
  GtkWidget *ajouterp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *annulerajoutp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label118;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label13;
  GtkWidget *label2;
  GtkWidget *fixed3;
  GtkWidget *nompdentry7;
  GtkWidget *adressempentry8;
  GtkWidget *idmpdentry9;
  GtkWidget *capacitempdentry10;
  GtkWidget *tarifmpdentry11;
  GtkObject *spin7_adj;
  GtkWidget *spin7;
  GtkObject *spin8_adj;
  GtkWidget *spin8;
  GtkObject *spin9_adj;
  GtkWidget *spin9;
  GtkObject *spin10_adj;
  GtkWidget *spin10;
  GtkObject *spin11_adj;
  GtkWidget *spin11;
  GtkObject *spin12_adj;
  GtkWidget *spin12;
  GtkWidget *eventbox1;
  GtkWidget *etatmpdcomboboxentry4;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *checkbutton2;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *annulermp;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label42;
  GtkWidget *menumodif;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label86;
  GtkWidget *modifiermp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label41;
  GtkWidget *verifier;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label70;
  GtkWidget *blocmpdcomboboxentry5;
  GtkWidget *abonmpdcomboboxentry6;
  GtkWidget *label108;
  GtkWidget *label110;
  GtkWidget *label109;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label40;
  GtkWidget *label39;
  GtkWidget *label3;
  GtkWidget *fixed4;
  GtkWidget *idsuppentry12;
  GtkWidget *supprimersup;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label46;
  GtkWidget *annulersup;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label47;
  GtkWidget *menusupp;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label87;
  GtkWidget *label44;
  GtkWidget *label43;
  GtkWidget *label4;
  GtkWidget *fixed11;
  GtkWidget *idtrvprk;
  GtkWidget *resulttrvprk;
  GtkWidget *mntrvp;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label93;
  GtkWidget *chercherprk;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label91;
  GtkWidget *annulertrvp;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label92;
  GtkWidget *label90;
  GtkWidget *label112;
  GtkWidget *chercherparking;
  GtkWidget *fixed5;
  GtkWidget *pragentry15;
  GtkWidget *cinagentry16;
  GtkWidget *resultaffectentry9;
  GtkWidget *affectag;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label57;
  GtkWidget *annuleraffag;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label58;
  GtkWidget *treeviewaffecteragent;
  GtkWidget *menuaffect;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label88;
  GtkWidget *label69;
  GtkWidget *actualiseraffecte;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image34;
  GtkWidget *label111;
  GtkWidget *label48;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label5;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_LEFT);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  id_entry = gtk_entry_new ();
  gtk_widget_show (id_entry);
  gtk_fixed_put (GTK_FIXED (fixed13), id_entry, 520, 344);
  gtk_widget_set_size_request (id_entry, 288, 67);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entry), 8226);

  password_entry = gtk_entry_new ();
  gtk_widget_show (password_entry);
  gtk_fixed_put (GTK_FIXED (fixed13), password_entry, 520, 464);
  gtk_widget_set_size_request (password_entry, 296, 59);
  gtk_entry_set_invisible_char (GTK_ENTRY (password_entry), 8226);

  accederlogin = gtk_button_new_with_mnemonic (_("acceder "));
  gtk_widget_show (accederlogin);
  gtk_fixed_put (GTK_FIXED (fixed13), accederlogin, 528, 760);
  gtk_widget_set_size_request (accederlogin, 264, 80);

  label115 = gtk_label_new (_("<span font_desc=\"10\" color='black'>ID_Administrateur : </span>"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed13), label115, 328, 352);
  gtk_widget_set_size_request (label115, 184, 56);
  gtk_label_set_use_markup (GTK_LABEL (label115), TRUE);

  label116 = gtk_label_new (_("<span font_desc=\"10\" color='black'>Password : </span>"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed13), label116, 296, 448);
  gtk_widget_set_size_request (label116, 200, 88);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  label114 = gtk_label_new (_("\n<span font_desc=\"20\" color='navy'> Acced\303\251 au parking parky  </span>"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed13), label114, 408, 56);
  gtk_widget_set_size_request (label114, 584, 176);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  label113 = gtk_label_new (_("page login "));
  gtk_widget_show (label113);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label113);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  treeviewparking = gtk_tree_view_new ();
  gtk_widget_show (treeviewparking);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewparking, 80, 272);
  gtk_widget_set_size_request (treeviewparking, 1136, 704);

  label6 = gtk_label_new (_(" <b><span color = \"green\">Afficher la liste des parking </span></b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 120, 72);
  gtk_widget_set_size_request (label6, 792, 64);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  actualiseraff = gtk_button_new ();
  gtk_widget_show (actualiseraff);
  gtk_fixed_put (GTK_FIXED (fixed1), actualiseraff, 1072, 200);
  gtk_widget_set_size_request (actualiseraff, 160, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (actualiseraff), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("\tactualiser"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  affecteraff = gtk_button_new ();
  gtk_widget_show (affecteraff);
  gtk_fixed_put (GTK_FIXED (fixed1), affecteraff, 888, 200);
  gtk_widget_set_size_request (affecteraff, 168, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (affecteraff), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  chercherchertrv = gtk_button_new ();
  gtk_widget_show (chercherchertrv);
  gtk_fixed_put (GTK_FIXED (fixed1), chercherchertrv, 712, 200);
  gtk_widget_set_size_request (chercherchertrv, 152, 56);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (chercherchertrv), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image32 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox32), image32, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox32), label97, FALSE, FALSE, 0);

  suppaff = gtk_button_new ();
  gtk_widget_show (suppaff);
  gtk_fixed_put (GTK_FIXED (fixed1), suppaff, 536, 200);
  gtk_widget_set_size_request (suppaff, 144, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (suppaff), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  modifaff = gtk_button_new ();
  gtk_widget_show (modifaff);
  gtk_fixed_put (GTK_FIXED (fixed1), modifaff, 320, 200);
  gtk_widget_set_size_request (modifaff, 176, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifaff), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("modifer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  ajotaff = gtk_button_new ();
  gtk_widget_show (ajotaff);
  gtk_fixed_put (GTK_FIXED (fixed1), ajotaff, 112, 200);
  gtk_widget_set_size_request (ajotaff, 176, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajotaff), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  retauloginbutton1 = gtk_button_new ();
  gtk_widget_show (retauloginbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), retauloginbutton1, 464, 1000);
  gtk_widget_set_size_request (retauloginbutton1, 288, 80);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (retauloginbutton1), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image35 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox35), image35, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("retour au login"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox35), label117, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  nompentry2 = gtk_entry_new ();
  gtk_widget_show (nompentry2);
  gtk_fixed_put (GTK_FIXED (fixed2), nompentry2, 528, 184);
  gtk_widget_set_size_request (nompentry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nompentry2), 8226);

  adrpentry3 = gtk_entry_new ();
  gtk_widget_show (adrpentry3);
  gtk_fixed_put (GTK_FIXED (fixed2), adrpentry3, 528, 248);
  gtk_widget_set_size_request (adrpentry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adrpentry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 528, 304);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  capacitepaentry5 = gtk_entry_new ();
  gtk_widget_show (capacitepaentry5);
  gtk_fixed_put (GTK_FIXED (fixed2), capacitepaentry5, 528, 440);
  gtk_widget_set_size_request (capacitepaentry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (capacitepaentry5), 8226);

  tarifpaentry6 = gtk_entry_new ();
  gtk_widget_show (tarifpaentry6);
  gtk_fixed_put (GTK_FIXED (fixed2), tarifpaentry6, 520, 560);
  gtk_widget_set_size_request (tarifpaentry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarifpaentry6), 8226);

  spin1_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spin1 = gtk_spin_button_new (GTK_ADJUSTMENT (spin1_adj), 1, 0);
  gtk_widget_show (spin1);
  gtk_fixed_put (GTK_FIXED (fixed2), spin1, 576, 784);
  gtk_widget_set_size_request (spin1, 60, 27);

  spin2_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spin2 = gtk_spin_button_new (GTK_ADJUSTMENT (spin2_adj), 1, 0);
  gtk_widget_show (spin2);
  gtk_fixed_put (GTK_FIXED (fixed2), spin2, 744, 784);
  gtk_widget_set_size_request (spin2, 60, 27);

  spin3_adj = gtk_adjustment_new (0, 0, 5000, 1, 10, 10);
  spin3 = gtk_spin_button_new (GTK_ADJUSTMENT (spin3_adj), 1, 0);
  gtk_widget_show (spin3);
  gtk_fixed_put (GTK_FIXED (fixed2), spin3, 960, 776);
  gtk_widget_set_size_request (spin3, 60, 27);

  spin4_adj = gtk_adjustment_new (27, 0, 31, 1, 10, 10);
  spin4 = gtk_spin_button_new (GTK_ADJUSTMENT (spin4_adj), 1, 0);
  gtk_widget_show (spin4);
  gtk_fixed_put (GTK_FIXED (fixed2), spin4, 576, 864);
  gtk_widget_set_size_request (spin4, 60, 27);

  spin5_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spin5 = gtk_spin_button_new (GTK_ADJUSTMENT (spin5_adj), 1, 0);
  gtk_widget_show (spin5);
  gtk_fixed_put (GTK_FIXED (fixed2), spin5, 744, 872);
  gtk_widget_set_size_request (spin5, 60, 27);

  spin6_adj = gtk_adjustment_new (1, 0, 5000, 1, 10, 10);
  spin6 = gtk_spin_button_new (GTK_ADJUSTMENT (spin6_adj), 1, 0);
  gtk_widget_show (spin6);
  gtk_fixed_put (GTK_FIXED (fixed2), spin6, 960, 864);
  gtk_widget_set_size_request (spin6, 60, 27);

  etatpcomboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (etatpcomboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), etatpcomboboxentry1, 528, 368);
  gtk_widget_set_size_request (etatpcomboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatpcomboboxentry1), _("vide"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatpcomboboxentry1), _("nonvide"));

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox2, 520, 504);
  gtk_widget_set_size_request (eventbox2, 189, 29);

  blocpacomboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (blocpacomboboxentry2);
  gtk_container_add (GTK_CONTAINER (eventbox2), blocpacomboboxentry2);
  gtk_widget_set_size_request (blocpacomboboxentry2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocpacomboboxentry2), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocpacomboboxentry2), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocpacomboboxentry2), _("C"));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("camion"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 640, 712);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("moto"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 760, 712);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  abonpacomboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (abonpacomboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed2), abonpacomboboxentry3, 520, 624);
  gtk_widget_set_size_request (abonpacomboboxentry3, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonpacomboboxentry3), _("annuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonpacomboboxentry3), _("mensuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonpacomboboxentry3), _("parjour"));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("voiture"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 512, 712);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label100 = gtk_label_new (_("<b><span color = \"blue\"> Jour  :</span></b>"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed2), label100, 504, 872);
  gtk_widget_set_size_request (label100, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label100), TRUE);

  label101 = gtk_label_new (_("<b><span color = \"blue\"> Mois :</span></b>"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed2), label101, 664, 784);
  gtk_widget_set_size_request (label101, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  label102 = gtk_label_new (_("<b><span color = \"blue\"> Mois :</span></b>"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed2), label102, 664, 880);
  gtk_widget_set_size_request (label102, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label102), TRUE);

  label104 = gtk_label_new (_("<b><span color = \"blue\"> Ann\303\251es :</span></b>"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed2), label104, 872, 864);
  gtk_widget_set_size_request (label104, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (label104), TRUE);

  label103 = gtk_label_new (_("<b><span color = \"blue\"> Ann\303\251es :</span></b>"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed2), label103, 872, 784);
  gtk_widget_set_size_request (label103, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label103), TRUE);

  label99 = gtk_label_new (_("<b><span color = \"blue\"> Jour  :</span></b>"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed2), label99, 504, 784);
  gtk_widget_set_size_request (label99, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 488, 976);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  menuajout = gtk_button_new ();
  gtk_widget_show (menuajout);
  gtk_fixed_put (GTK_FIXED (fixed2), menuajout, 872, 1016);
  gtk_widget_set_size_request (menuajout, 240, 96);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (menuajout), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("menu"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox24), label85, FALSE, FALSE, 0);

  ajouterp = gtk_button_new ();
  gtk_widget_show (ajouterp);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouterp, 352, 1024);
  gtk_widget_set_size_request (ajouterp, 200, 85);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ajouterp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7), label26, FALSE, FALSE, 0);

  annulerajoutp = gtk_button_new ();
  gtk_widget_show (annulerajoutp);
  gtk_fixed_put (GTK_FIXED (fixed2), annulerajoutp, 608, 1016);
  gtk_widget_set_size_request (annulerajoutp, 216, 93);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (annulerajoutp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("<b><span color = \"black\"> Nom_Parking :</span></b>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 368, 184);
  gtk_widget_set_size_request (label14, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label15 = gtk_label_new (_("<b><span color = \"black\"> Adresse  :</span></b>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 360, 248);
  gtk_widget_set_size_request (label15, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("<b><span color = \"black\"> ID_Parking :</span></b>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 352, 312);
  gtk_widget_set_size_request (label16, 112, 17);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("<b><span color = \"black\"> Etat  :</span></b>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 352, 384);
  gtk_widget_set_size_request (label17, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<b><span color = \"black\"> Capacit\303\251 :</span></b>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 344, 440);
  gtk_widget_set_size_request (label18, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<b><span color = \"black\"> Bloc  :</span></b>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 344, 512);
  gtk_widget_set_size_request (label19, 96, 40);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<b><span color = \"black\"> Tarif  :</span></b>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 368, 584);
  gtk_widget_set_size_request (label20, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label21 = gtk_label_new (_("<b><span color = \"black\"> Abonnement  :</span></b>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 368, 624);
  gtk_widget_set_size_request (label21, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label118 = gtk_label_new (_("<b><span color = \"black\"> V\303\251hicule  :</span></b>"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed2), label118, 320, 704);
  gtk_widget_set_size_request (label118, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label118), TRUE);

  label23 = gtk_label_new (_("<b><span color = \"black\"> Date_D\303\251but :</span></b>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 352, 776);
  gtk_widget_set_size_request (label23, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<b><span color = \"black\"> Date_Fin :</span></b>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 352, 880);
  gtk_widget_set_size_request (label24, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<b><span color = \"black\"> Acc\303\251es  :</span></b>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 360, 968);
  gtk_widget_set_size_request (label25, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label13 = gtk_label_new (_("<b><span color = \"red\"> Ajout_et_gestion_de_perking </span></b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 432, 16);
  gtk_widget_set_size_request (label13, 280, 88);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label2 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  nompdentry7 = gtk_entry_new ();
  gtk_widget_show (nompdentry7);
  gtk_fixed_put (GTK_FIXED (fixed3), nompdentry7, 296, 128);
  gtk_widget_set_size_request (nompdentry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nompdentry7), 8226);

  adressempentry8 = gtk_entry_new ();
  gtk_widget_show (adressempentry8);
  gtk_fixed_put (GTK_FIXED (fixed3), adressempentry8, 296, 176);
  gtk_widget_set_size_request (adressempentry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adressempentry8), 8226);

  idmpdentry9 = gtk_entry_new ();
  gtk_widget_show (idmpdentry9);
  gtk_fixed_put (GTK_FIXED (fixed3), idmpdentry9, 296, 240);
  gtk_widget_set_size_request (idmpdentry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idmpdentry9), 8226);

  capacitempdentry10 = gtk_entry_new ();
  gtk_widget_show (capacitempdentry10);
  gtk_fixed_put (GTK_FIXED (fixed3), capacitempdentry10, 296, 360);
  gtk_widget_set_size_request (capacitempdentry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (capacitempdentry10), 8226);

  tarifmpdentry11 = gtk_entry_new ();
  gtk_widget_show (tarifmpdentry11);
  gtk_fixed_put (GTK_FIXED (fixed3), tarifmpdentry11, 296, 472);
  gtk_widget_set_size_request (tarifmpdentry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tarifmpdentry11), 8226);

  spin7_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spin7 = gtk_spin_button_new (GTK_ADJUSTMENT (spin7_adj), 1, 0);
  gtk_widget_show (spin7);
  gtk_fixed_put (GTK_FIXED (fixed3), spin7, 392, 696);
  gtk_widget_set_size_request (spin7, 60, 27);

  spin8_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spin8 = gtk_spin_button_new (GTK_ADJUSTMENT (spin8_adj), 1, 0);
  gtk_widget_show (spin8);
  gtk_fixed_put (GTK_FIXED (fixed3), spin8, 568, 696);
  gtk_widget_set_size_request (spin8, 60, 27);

  spin9_adj = gtk_adjustment_new (1, 0, 5000, 1, 10, 10);
  spin9 = gtk_spin_button_new (GTK_ADJUSTMENT (spin9_adj), 1, 0);
  gtk_widget_show (spin9);
  gtk_fixed_put (GTK_FIXED (fixed3), spin9, 816, 688);
  gtk_widget_set_size_request (spin9, 60, 27);

  spin10_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spin10 = gtk_spin_button_new (GTK_ADJUSTMENT (spin10_adj), 1, 0);
  gtk_widget_show (spin10);
  gtk_fixed_put (GTK_FIXED (fixed3), spin10, 392, 768);
  gtk_widget_set_size_request (spin10, 60, 27);

  spin11_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spin11 = gtk_spin_button_new (GTK_ADJUSTMENT (spin11_adj), 1, 0);
  gtk_widget_show (spin11);
  gtk_fixed_put (GTK_FIXED (fixed3), spin11, 568, 768);
  gtk_widget_set_size_request (spin11, 60, 27);

  spin12_adj = gtk_adjustment_new (1, 0, 5000, 1, 10, 10);
  spin12 = gtk_spin_button_new (GTK_ADJUSTMENT (spin12_adj), 1, 0);
  gtk_widget_show (spin12);
  gtk_fixed_put (GTK_FIXED (fixed3), spin12, 816, 760);
  gtk_widget_set_size_request (spin12, 60, 27);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox1, 296, 296);
  gtk_widget_set_size_request (eventbox1, 189, 29);

  etatmpdcomboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (etatmpdcomboboxentry4);
  gtk_container_add (GTK_CONTAINER (eventbox1), etatmpdcomboboxentry4);
  gtk_widget_set_size_request (etatmpdcomboboxentry4, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatmpdcomboboxentry4), _("vide"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatmpdcomboboxentry4), _("nonvide"));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("voiture "));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 296, 608);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("camion "));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5, 464, 608);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("moto"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton6, 576, 608);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 296, 880);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  label105 = gtk_label_new (_("<b><span color = \"blue\"> Jour  :</span></b>"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed3), label105, 320, 704);
  gtk_widget_set_size_request (label105, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  label106 = gtk_label_new (_("<b><span color = \"blue\"> Jour  :</span></b>"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed3), label106, 320, 776);
  gtk_widget_set_size_request (label106, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  label107 = gtk_label_new (_("<b><span color = \"blue\"> Mois  :</span></b>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed3), label107, 488, 704);
  gtk_widget_set_size_request (label107, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  annulermp = gtk_button_new ();
  gtk_widget_show (annulermp);
  gtk_fixed_put (GTK_FIXED (fixed3), annulermp, 328, 976);
  gtk_widget_set_size_request (annulermp, 208, 96);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (annulermp), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox10), label42, FALSE, FALSE, 0);

  menumodif = gtk_button_new ();
  gtk_widget_show (menumodif);
  gtk_fixed_put (GTK_FIXED (fixed3), menumodif, 584, 976);
  gtk_widget_set_size_request (menumodif, 248, 96);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (menumodif), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("menu"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox25), label86, FALSE, FALSE, 0);

  modifiermp = gtk_button_new ();
  gtk_widget_show (modifiermp);
  gtk_fixed_put (GTK_FIXED (fixed3), modifiermp, 72, 976);
  gtk_widget_set_size_request (modifiermp, 216, 96);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (modifiermp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox9), label41, FALSE, FALSE, 0);

  verifier = gtk_button_new ();
  gtk_widget_show (verifier);
  gtk_fixed_put (GTK_FIXED (fixed3), verifier, 592, 200);
  gtk_widget_set_size_request (verifier, 384, 96);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (verifier), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("verifier"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox19), label70, FALSE, FALSE, 0);

  blocmpdcomboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (blocmpdcomboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed3), blocmpdcomboboxentry5, 296, 408);
  gtk_widget_set_size_request (blocmpdcomboboxentry5, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocmpdcomboboxentry5), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocmpdcomboboxentry5), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (blocmpdcomboboxentry5), _("C"));

  abonmpdcomboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (abonmpdcomboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed3), abonmpdcomboboxentry6, 296, 528);
  gtk_widget_set_size_request (abonmpdcomboboxentry6, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonmpdcomboboxentry6), _("annuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonmpdcomboboxentry6), _("mensuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (abonmpdcomboboxentry6), _("parjour"));

  label108 = gtk_label_new (_("<b><span color = \"blue\"> Ann\303\251es  :</span></b>"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed3), label108, 712, 688);
  gtk_widget_set_size_request (label108, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label110 = gtk_label_new (_("<b><span color = \"blue\"> Ann\303\251es  :</span></b>"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed3), label110, 712, 760);
  gtk_widget_set_size_request (label110, 80, 32);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  label109 = gtk_label_new (_("<b><span color = \"blue\"> Mois  :</span></b>"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed3), label109, 488, 776);
  gtk_widget_set_size_request (label109, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  label28 = gtk_label_new (_("<b><span color = \"red\">Modification_D'un_Parking</span></b>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 264, 48);
  gtk_widget_set_size_request (label28, 200, 32);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("<b><span color = \"black\"> Nom_Parking :</span></b>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 104, 104);
  gtk_widget_set_size_request (label29, 144, 72);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<b><span color = \"black\"> Adresse :</span></b>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 80, 168);
  gtk_widget_set_size_request (label30, 160, 56);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label31 = gtk_label_new (_("<b><span color = \"black\"> ID_Parking :</span></b>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed3), label31, 80, 224);
  gtk_widget_set_size_request (label31, 184, 56);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label32 = gtk_label_new (_("<b><span color = \"black\"> Etat :</span></b>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed3), label32, 88, 288);
  gtk_widget_set_size_request (label32, 120, 40);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label33 = gtk_label_new (_("<b><span color = \"black\"> Capacit\303\251 :</span></b>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 72, 344);
  gtk_widget_set_size_request (label33, 168, 48);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("<b><span color = \"black\"> Bloc  :</span></b>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 88, 392);
  gtk_widget_set_size_request (label34, 120, 56);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label35 = gtk_label_new (_("<b><span color = \"black\"> Tarif :</span></b>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 88, 464);
  gtk_widget_set_size_request (label35, 105, 48);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label36 = gtk_label_new (_("<b><span color = \"black\"> Abonnement :</span></b>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed3), label36, 104, 528);
  gtk_widget_set_size_request (label36, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<b><span color = \"black\"> V\303\251hicules :</span></b>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 88, 592);
  gtk_widget_set_size_request (label37, 128, 49);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("<b><span color = \"black\"> Date_D\303\251but  :</span></b>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 88, 680);
  gtk_widget_set_size_request (label38, 160, 56);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label40 = gtk_label_new (_("<b><span color = \"black\"> Date_Fin  :</span></b>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed3), label40, 80, 752);
  gtk_widget_set_size_request (label40, 152, 72);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label39 = gtk_label_new (_("<b><span color = \"black\"> Acc\303\251es  :</span></b>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed3), label39, 80, 864);
  gtk_widget_set_size_request (label39, 160, 56);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label3 = gtk_label_new (_("Modifier "));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  idsuppentry12 = gtk_entry_new ();
  gtk_widget_show (idsuppentry12);
  gtk_fixed_put (GTK_FIXED (fixed4), idsuppentry12, 296, 208);
  gtk_widget_set_size_request (idsuppentry12, 224, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (idsuppentry12), 8226);

  supprimersup = gtk_button_new ();
  gtk_widget_show (supprimersup);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimersup, 144, 320);
  gtk_widget_set_size_request (supprimersup, 216, 72);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (supprimersup), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox11), label46, FALSE, FALSE, 0);

  annulersup = gtk_button_new ();
  gtk_widget_show (annulersup);
  gtk_fixed_put (GTK_FIXED (fixed4), annulersup, 424, 320);
  gtk_widget_set_size_request (annulersup, 224, 69);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (annulersup), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox12), label47, FALSE, FALSE, 0);

  menusupp = gtk_button_new ();
  gtk_widget_show (menusupp);
  gtk_fixed_put (GTK_FIXED (fixed4), menusupp, 312, 448);
  gtk_widget_set_size_request (menusupp, 144, 72);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (menusupp), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("menu"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox26), label87, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("<b><span color = \"black\"> ID_Parking :</span></b>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 120, 208);
  gtk_widget_set_size_request (label44, 176, 72);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label43 = gtk_label_new (_("<b><span color = \"red\">Suppression_D'un_Parking</span></b>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed4), label43, 256, 96);
  gtk_widget_set_size_request (label43, 232, 65);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label4 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label4);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  idtrvprk = gtk_entry_new ();
  gtk_widget_show (idtrvprk);
  gtk_fixed_put (GTK_FIXED (fixed11), idtrvprk, 360, 168);
  gtk_widget_set_size_request (idtrvprk, 264, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (idtrvprk), 8226);

  resulttrvprk = gtk_entry_new ();
  gtk_widget_show (resulttrvprk);
  gtk_fixed_put (GTK_FIXED (fixed11), resulttrvprk, 16, 336);
  gtk_widget_set_size_request (resulttrvprk, 896, 104);
  gtk_entry_set_invisible_char (GTK_ENTRY (resulttrvprk), 8226);

  mntrvp = gtk_button_new ();
  gtk_widget_show (mntrvp);
  gtk_fixed_put (GTK_FIXED (fixed11), mntrvp, 928, 368);
  gtk_widget_set_size_request (mntrvp, 224, 72);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (mntrvp), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("menu"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox30), label93, FALSE, FALSE, 0);

  chercherprk = gtk_button_new ();
  gtk_widget_show (chercherprk);
  gtk_fixed_put (GTK_FIXED (fixed11), chercherprk, 928, 176);
  gtk_widget_set_size_request (chercherprk, 224, 72);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (chercherprk), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox28), label91, FALSE, FALSE, 0);

  annulertrvp = gtk_button_new ();
  gtk_widget_show (annulertrvp);
  gtk_fixed_put (GTK_FIXED (fixed11), annulertrvp, 928, 264);
  gtk_widget_set_size_request (annulertrvp, 224, 72);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (annulertrvp), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox29), label92, FALSE, FALSE, 0);

  label90 = gtk_label_new (_("<b><span color = \"black\"> ID_Parking_a_Trouver :</span></b>"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed11), label90, 104, 184);
  gtk_widget_set_size_request (label90, 240, 48);
  gtk_label_set_use_markup (GTK_LABEL (label90), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label90), 0.5, 0.48);

  label112 = gtk_label_new (_("<b><span color = \"red\"> Chercher_Un_Parking</span></b>"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed11), label112, 280, 24);
  gtk_widget_set_size_request (label112, 464, 72);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  chercherparking = gtk_label_new (_("chercher parking"));
  gtk_widget_show (chercherparking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), chercherparking);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  pragentry15 = gtk_entry_new ();
  gtk_widget_show (pragentry15);
  gtk_fixed_put (GTK_FIXED (fixed5), pragentry15, 328, 160);
  gtk_widget_set_size_request (pragentry15, 232, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (pragentry15), 8226);

  cinagentry16 = gtk_entry_new ();
  gtk_widget_show (cinagentry16);
  gtk_fixed_put (GTK_FIXED (fixed5), cinagentry16, 328, 272);
  gtk_widget_set_size_request (cinagentry16, 240, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinagentry16), 8226);

  resultaffectentry9 = gtk_entry_new ();
  gtk_widget_show (resultaffectentry9);
  gtk_fixed_put (GTK_FIXED (fixed5), resultaffectentry9, 120, 464);
  gtk_widget_set_size_request (resultaffectentry9, 768, 104);
  gtk_entry_set_invisible_char (GTK_ENTRY (resultaffectentry9), 8226);

  affectag = gtk_button_new ();
  gtk_widget_show (affectag);
  gtk_fixed_put (GTK_FIXED (fixed5), affectag, 144, 632);
  gtk_widget_set_size_request (affectag, 304, 104);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (affectag), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("affecter "));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox13), label57, FALSE, FALSE, 0);

  annuleraffag = gtk_button_new ();
  gtk_widget_show (annuleraffag);
  gtk_fixed_put (GTK_FIXED (fixed5), annuleraffag, 496, 632);
  gtk_widget_set_size_request (annuleraffag, 376, 112);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (annuleraffag), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox14), label58, FALSE, FALSE, 0);

  treeviewaffecteragent = gtk_tree_view_new ();
  gtk_widget_show (treeviewaffecteragent);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewaffecteragent, 808, 152);
  gtk_widget_set_size_request (treeviewaffecteragent, 480, 288);

  menuaffect = gtk_button_new ();
  gtk_widget_show (menuaffect);
  gtk_fixed_put (GTK_FIXED (fixed5), menuaffect, 304, 824);
  gtk_widget_set_size_request (menuaffect, 352, 112);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (menuaffect), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("menu"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox27), label88, FALSE, FALSE, 0);

  label69 = gtk_label_new (_("<b><span color = \"blue\"> Agent affect\303\251e a un parking </span></b>"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed5), label69, 936, 80);
  gtk_widget_set_size_request (label69, 304, 72);
  gtk_label_set_use_markup (GTK_LABEL (label69), TRUE);

  actualiseraffecte = gtk_button_new ();
  gtk_widget_show (actualiseraffecte);
  gtk_fixed_put (GTK_FIXED (fixed5), actualiseraffecte, 1000, 472);
  gtk_widget_set_size_request (actualiseraffecte, 186, 88);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (actualiseraffecte), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image34 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox34), image34, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox34), label111, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("<b><span color = \"red\"> Affecter_Un_Agent_a_Un_Parking</span></b>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed5), label48, 400, 16);
  gtk_widget_set_size_request (label48, 288, 96);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  label50 = gtk_label_new (_("<b><span color = \"black\"> ID_Parking :</span></b>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed5), label50, 160, 168);
  gtk_widget_set_size_request (label50, 144, 64);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label51 = gtk_label_new (_("<b><span color = \"black\"> CIN_D'agent :</span></b>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 152, 280);
  gtk_widget_set_size_request (label51, 128, 64);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label5 = gtk_label_new (_("Affecter Agent"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label5);
  gtk_misc_set_alignment (GTK_MISC (label5), 0.5, 0.54);

  g_signal_connect ((gpointer) accederlogin, "clicked",
                    G_CALLBACK (on_accederlogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewparking, "row_activated",
                    G_CALLBACK (on_treeviewparking_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiseraff, "clicked",
                    G_CALLBACK (on_actualiseraff_clicked),
                    NULL);
  g_signal_connect ((gpointer) affecteraff, "clicked",
                    G_CALLBACK (on_affecteraff_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercherchertrv, "clicked",
                    G_CALLBACK (on_chercherchertrv_clicked),
                    NULL);
  g_signal_connect ((gpointer) suppaff, "clicked",
                    G_CALLBACK (on_suppaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifaff, "clicked",
                    G_CALLBACK (on_modifaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajotaff, "clicked",
                    G_CALLBACK (on_ajotaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) retauloginbutton1, "clicked",
                    G_CALLBACK (on_retauloginbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) menuajout, "clicked",
                    G_CALLBACK (on_menuajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterp, "clicked",
                    G_CALLBACK (on_ajouterp_clicked),
                    NULL);
  g_signal_connect ((gpointer) annulerajoutp, "clicked",
                    G_CALLBACK (on_annulerajoutp_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) annulermp, "clicked",
                    G_CALLBACK (on_annulermp_clicked),
                    NULL);
  g_signal_connect ((gpointer) menumodif, "clicked",
                    G_CALLBACK (on_menumodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifiermp, "clicked",
                    G_CALLBACK (on_modifiermp_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifier, "clicked",
                    G_CALLBACK (on_verifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimersup, "clicked",
                    G_CALLBACK (on_supprimersup_clicked),
                    NULL);
  g_signal_connect ((gpointer) annulersup, "clicked",
                    G_CALLBACK (on_annulersup_clicked),
                    NULL);
  g_signal_connect ((gpointer) menusupp, "clicked",
                    G_CALLBACK (on_menusupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) mntrvp, "clicked",
                    G_CALLBACK (on_mntrvp_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercherprk, "clicked",
                    G_CALLBACK (on_chercherprk_clicked),
                    NULL);
  g_signal_connect ((gpointer) annulertrvp, "clicked",
                    G_CALLBACK (on_annulertrvp_clicked),
                    NULL);
  g_signal_connect ((gpointer) affectag, "clicked",
                    G_CALLBACK (on_affectag_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuleraffag, "clicked",
                    G_CALLBACK (on_annuleraffag_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewaffecteragent, "row_activated",
                    G_CALLBACK (on_treeviewaffecteragent_row_activated),
                    NULL);
  g_signal_connect ((gpointer) menuaffect, "clicked",
                    G_CALLBACK (on_menuaffect_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiseraffecte, "clicked",
                    G_CALLBACK (on_actualiseraffecte_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window1, id_entry, "id_entry");
  GLADE_HOOKUP_OBJECT (window1, password_entry, "password_entry");
  GLADE_HOOKUP_OBJECT (window1, accederlogin, "accederlogin");
  GLADE_HOOKUP_OBJECT (window1, label115, "label115");
  GLADE_HOOKUP_OBJECT (window1, label116, "label116");
  GLADE_HOOKUP_OBJECT (window1, label114, "label114");
  GLADE_HOOKUP_OBJECT (window1, label113, "label113");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, treeviewparking, "treeviewparking");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, actualiseraff, "actualiseraff");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, affecteraff, "affecteraff");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, chercherchertrv, "chercherchertrv");
  GLADE_HOOKUP_OBJECT (window1, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window1, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window1, image32, "image32");
  GLADE_HOOKUP_OBJECT (window1, label97, "label97");
  GLADE_HOOKUP_OBJECT (window1, suppaff, "suppaff");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, modifaff, "modifaff");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, ajotaff, "ajotaff");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, retauloginbutton1, "retauloginbutton1");
  GLADE_HOOKUP_OBJECT (window1, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (window1, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (window1, image35, "image35");
  GLADE_HOOKUP_OBJECT (window1, label117, "label117");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, nompentry2, "nompentry2");
  GLADE_HOOKUP_OBJECT (window1, adrpentry3, "adrpentry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, capacitepaentry5, "capacitepaentry5");
  GLADE_HOOKUP_OBJECT (window1, tarifpaentry6, "tarifpaentry6");
  GLADE_HOOKUP_OBJECT (window1, spin1, "spin1");
  GLADE_HOOKUP_OBJECT (window1, spin2, "spin2");
  GLADE_HOOKUP_OBJECT (window1, spin3, "spin3");
  GLADE_HOOKUP_OBJECT (window1, spin4, "spin4");
  GLADE_HOOKUP_OBJECT (window1, spin5, "spin5");
  GLADE_HOOKUP_OBJECT (window1, spin6, "spin6");
  GLADE_HOOKUP_OBJECT (window1, etatpcomboboxentry1, "etatpcomboboxentry1");
  GLADE_HOOKUP_OBJECT (window1, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (window1, blocpacomboboxentry2, "blocpacomboboxentry2");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window1, abonpacomboboxentry3, "abonpacomboboxentry3");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, label100, "label100");
  GLADE_HOOKUP_OBJECT (window1, label101, "label101");
  GLADE_HOOKUP_OBJECT (window1, label102, "label102");
  GLADE_HOOKUP_OBJECT (window1, label104, "label104");
  GLADE_HOOKUP_OBJECT (window1, label103, "label103");
  GLADE_HOOKUP_OBJECT (window1, label99, "label99");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, menuajout, "menuajout");
  GLADE_HOOKUP_OBJECT (window1, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window1, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, ajouterp, "ajouterp");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, annulerajoutp, "annulerajoutp");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, label118, "label118");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, nompdentry7, "nompdentry7");
  GLADE_HOOKUP_OBJECT (window1, adressempentry8, "adressempentry8");
  GLADE_HOOKUP_OBJECT (window1, idmpdentry9, "idmpdentry9");
  GLADE_HOOKUP_OBJECT (window1, capacitempdentry10, "capacitempdentry10");
  GLADE_HOOKUP_OBJECT (window1, tarifmpdentry11, "tarifmpdentry11");
  GLADE_HOOKUP_OBJECT (window1, spin7, "spin7");
  GLADE_HOOKUP_OBJECT (window1, spin8, "spin8");
  GLADE_HOOKUP_OBJECT (window1, spin9, "spin9");
  GLADE_HOOKUP_OBJECT (window1, spin10, "spin10");
  GLADE_HOOKUP_OBJECT (window1, spin11, "spin11");
  GLADE_HOOKUP_OBJECT (window1, spin12, "spin12");
  GLADE_HOOKUP_OBJECT (window1, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window1, etatmpdcomboboxentry4, "etatmpdcomboboxentry4");
  GLADE_HOOKUP_OBJECT (window1, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window1, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window1, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window1, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window1, label105, "label105");
  GLADE_HOOKUP_OBJECT (window1, label106, "label106");
  GLADE_HOOKUP_OBJECT (window1, label107, "label107");
  GLADE_HOOKUP_OBJECT (window1, annulermp, "annulermp");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, menumodif, "menumodif");
  GLADE_HOOKUP_OBJECT (window1, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label86, "label86");
  GLADE_HOOKUP_OBJECT (window1, modifiermp, "modifiermp");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, verifier, "verifier");
  GLADE_HOOKUP_OBJECT (window1, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1, image19, "image19");
  GLADE_HOOKUP_OBJECT (window1, label70, "label70");
  GLADE_HOOKUP_OBJECT (window1, blocmpdcomboboxentry5, "blocmpdcomboboxentry5");
  GLADE_HOOKUP_OBJECT (window1, abonmpdcomboboxentry6, "abonmpdcomboboxentry6");
  GLADE_HOOKUP_OBJECT (window1, label108, "label108");
  GLADE_HOOKUP_OBJECT (window1, label110, "label110");
  GLADE_HOOKUP_OBJECT (window1, label109, "label109");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, idsuppentry12, "idsuppentry12");
  GLADE_HOOKUP_OBJECT (window1, supprimersup, "supprimersup");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, annulersup, "annulersup");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, menusupp, "menusupp");
  GLADE_HOOKUP_OBJECT (window1, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window1, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, label87, "label87");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window1, idtrvprk, "idtrvprk");
  GLADE_HOOKUP_OBJECT (window1, resulttrvprk, "resulttrvprk");
  GLADE_HOOKUP_OBJECT (window1, mntrvp, "mntrvp");
  GLADE_HOOKUP_OBJECT (window1, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window1, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window1, image30, "image30");
  GLADE_HOOKUP_OBJECT (window1, label93, "label93");
  GLADE_HOOKUP_OBJECT (window1, chercherprk, "chercherprk");
  GLADE_HOOKUP_OBJECT (window1, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window1, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label91, "label91");
  GLADE_HOOKUP_OBJECT (window1, annulertrvp, "annulertrvp");
  GLADE_HOOKUP_OBJECT (window1, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window1, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, label92, "label92");
  GLADE_HOOKUP_OBJECT (window1, label90, "label90");
  GLADE_HOOKUP_OBJECT (window1, label112, "label112");
  GLADE_HOOKUP_OBJECT (window1, chercherparking, "chercherparking");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, pragentry15, "pragentry15");
  GLADE_HOOKUP_OBJECT (window1, cinagentry16, "cinagentry16");
  GLADE_HOOKUP_OBJECT (window1, resultaffectentry9, "resultaffectentry9");
  GLADE_HOOKUP_OBJECT (window1, affectag, "affectag");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, annuleraffag, "annuleraffag");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label58, "label58");
  GLADE_HOOKUP_OBJECT (window1, treeviewaffecteragent, "treeviewaffecteragent");
  GLADE_HOOKUP_OBJECT (window1, menuaffect, "menuaffect");
  GLADE_HOOKUP_OBJECT (window1, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window1, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window1, image27, "image27");
  GLADE_HOOKUP_OBJECT (window1, label88, "label88");
  GLADE_HOOKUP_OBJECT (window1, label69, "label69");
  GLADE_HOOKUP_OBJECT (window1, actualiseraffecte, "actualiseraffecte");
  GLADE_HOOKUP_OBJECT (window1, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (window1, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window1, image34, "image34");
  GLADE_HOOKUP_OBJECT (window1, label111, "label111");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");

  return window1;
}

